version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - log-net

  app1:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    container_name: app1
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    networks:
      - log-net
    depends_on:
      - elasticsearch

  app2:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    container_name: app2
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    networks:
      - log-net
    depends_on:
      - elasticsearch

  app3:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    container_name: app3
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    networks:
      - log-net
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - log-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4000:4000"
    networks:
      - log-net

networks:
  log-net:
    driver: bridge